api: https://www.mapbox.com/core
tileApi: https://api.mapbox.com
env: production
url: https://www.mapbox.com
versions:
  - 2.1
  - 2.0
  - 1.0.1
  - 1.0.0
spec_url: https://github.com/mapbox/vector-tile-spec/
version_url: https://github.com/mapbox/vector-tile-spec/tree/master/
current: 2.1
permalink: /:categories/:title/
baseurl: /vector-tiles
accessToken: pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpejY4M29iazA2Z2gycXA4N2pmbDZmangifQ.-g_vE53SD2WrJ6tFX7QHmA
